org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

## Environment Properties
minecraft_version_range=[1.21.3,1.22)
forge_version_range=[0,)
loader_version_range=[0,)
minecraft_version=1.21.3
forge_version=53.1.0
mod_name=Stable FPS
mod_id=stablefps
mod_license=MIT
mod_version=1.0.2
mod_group_id=patrolin.stablefps
mod_authors=Patrolin
mod_description=Minecraft mod to fix long-standing FPS stability issues.